#!/bin/bash

###############################################################################
# DocSync Pre-commit Hook Installer
#
# This script installs a pre-commit git hook that runs DocSync to check
# for documentation updates when code files are changed.
#
# Usage: ./install-hook.sh
# Run this script from any git repository to install the hook.
###############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 DocSync Pre-commit Hook Installer${NC}\n"

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo -e "${RED}❌ Error: Not a git repository${NC}"
    echo "   Please run this script from the root of a git repository."
    exit 1
fi

echo -e "${GREEN}✓${NC} Git repository detected"

# Get the absolute path to the CLI script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CLI_PATH="${SCRIPT_DIR}/index.js"

# Verify the CLI script exists
if [ ! -f "$CLI_PATH" ]; then
    echo -e "${RED}❌ Error: CLI script not found at ${CLI_PATH}${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} DocSync CLI found at: ${CLI_PATH}"

# Create the hooks directory if it doesn't exist
HOOKS_DIR=".git/hooks"
if [ ! -d "$HOOKS_DIR" ]; then
    mkdir -p "$HOOKS_DIR"
    echo -e "${GREEN}✓${NC} Created hooks directory"
fi

# Path to the pre-commit hook
HOOK_PATH="${HOOKS_DIR}/pre-commit"

# Check if a pre-commit hook already exists
if [ -f "$HOOK_PATH" ]; then
    echo -e "${YELLOW}⚠${NC}  Pre-commit hook already exists"
    read -p "   Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Installation cancelled${NC}"
        exit 0
    fi
    # Backup existing hook
    BACKUP_PATH="${HOOK_PATH}.backup.$(date +%s)"
    cp "$HOOK_PATH" "$BACKUP_PATH"
    echo -e "${GREEN}✓${NC} Backed up existing hook to: ${BACKUP_PATH}"
fi

# Create the pre-commit hook
cat > "$HOOK_PATH" << EOF
#!/bin/bash
###############################################################################
# DocSync Pre-commit Hook
# Auto-generated by install-hook.sh
# 
# This hook runs DocSync to check for documentation updates when code changes.
###############################################################################

# Run DocSync CLI
node "$CLI_PATH"

# Capture exit code
EXIT_CODE=\$?

# Always allow commit (exit 0) even if DocSync fails
# This ensures commits aren't blocked by documentation checks
exit 0
EOF

# Make the hook executable
chmod +x "$HOOK_PATH"

echo -e "${GREEN}✓${NC} Pre-commit hook installed successfully"
echo -e "${GREEN}✓${NC} Hook made executable"

# Summary
echo -e "\n${BLUE}📋 Installation Summary:${NC}"
echo "   Hook location: ${HOOK_PATH}"
echo "   CLI location:  ${CLI_PATH}"
echo "   Status:        Active"

echo -e "\n${GREEN}✅ Installation complete!${NC}"
echo -e "   The pre-commit hook will now run automatically before each commit."
echo -e "   It will analyze .js and .ts file changes and check documentation."

# Test the hook
echo -e "\n${BLUE}🧪 Testing the hook...${NC}"
if bash "$HOOK_PATH"; then
    echo -e "${GREEN}✓${NC} Hook test passed"
else
    echo -e "${YELLOW}⚠${NC}  Hook test completed (non-zero exit is OK for testing)"
fi

echo -e "\n${BLUE}💡 Tip:${NC} To temporarily skip the hook, use: git commit --no-verify"

# Made with Bob